name: build
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          repository: OpenEtherCATsociety/SOEM
          path: 'SOEM'
          submodules: true
      - run: cd SOEM
      - name: Configure
        shell: bash
        run: |
          cmake -E make_directory build
          cmake -B build -S . \
             -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      - name: Build
        shell: bash
        run: |
          cmake --build build -j4 --target install
