name: build
on: [push, pull_request]
env:
  BUILD_TYPE: Release
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-20.04

    steps:
      - name: clone SOEM
        uses: actions/checkout@v3
        with:
          path: 'SOEM'
          repository: OpenEtherCATsociety/SOEM
          submodules: true
      - run:
          ls
          
      - name: Configure SOEM
        run: |
          cmake -E make_directory $GITHUB_WORKSPACE/SOEM/build
          cmake -B $GITHUB_WORKSPACE/SOEM/build -S $GITHUB_WORKSPACE/SOEM \
             -DCMAKE_BUILD_TYPE=$BUILD_TYPE
      
      - name: Build SOEM
        run:
          cmake --build $GITHUB_WORKSPACE/SOEM/build -j4 --target install
